node {
    stage("Checkout Git Repo")
    {
      checkout scm
    }

    stage("build & SonarQube analysis") {
         withSonarQubeEnv('sonar-qube') {
          docker.withTool('docker-test'){
            docker.withServer('tcp://my-docker:2376','docker-server-certs'){

            docker.image('quay.io/zgrinber/maven:test3').inside{

                     sh 'mvn clean package sonar:sonar'
                  }
           }
      }
    }
  }
      stage("Quality Gate"){
          timeout(time: 1, unit: 'HOURS') {
              def qg = waitForQualityGate()
              if (qg.status != 'OK') {
                  error "Pipeline aborted due to quality gate failure: ${qg.status}"
              }
          }
      }
    stage("Clean Workspace")
       {
          cleanWs()

       }

}
